### ISSUE TITLE
Device manager not detecting board plug / unplug

### ISSUE THREAD

**Issue by VVESTM** [ARM-software/vscode-device-manager#1]
Type: Bug Report

While using VSCode with Arm Device Manager, it is not detecting when I plug a new board. See following captures with sequence : 

1. launch VSCode and plug board via USB. **Nothing appear in the device manager.**
![image](https://user-images.githubusercontent.com/22098252/223173722-d2ebb7ad-b26c-4e11-91a9-b6b8c3e2be05.png)

2. relaunch VSCode : we can see the board.
![image](https://user-images.githubusercontent.com/22098252/223174350-55c3efad-0f92-4baa-a283-070fc848a16c.png)

3. unplug board and replace by an other one. **We can see the old board is removed but the new one is not added.**
![image](https://user-images.githubusercontent.com/22098252/223174591-324064e5-83bf-42d2-a6ab-2d561f484a16.png)

4. relaunch VSCode : we can see the new board.
![image](https://user-images.githubusercontent.com/22098252/223174706-94509fe2-22c9-4ba4-bf36-5f4d6c259a48.png)

- OS and Version: Windows
- VS Code Version: 1.76.0
- Extension Version: v1.5.0
- Target Device: NUCLEO-U575ZI-Q, B-U585I-IOT02A (but I think we will have the same with any other HW)

**Expected behavior**
The device manager should show the connected device, even when there are plug / unplug.

**Comment by thegecko** [comment]
Thanks, this is a very timely bug report as I think we have identified a workaround for this issue in the underlying `usb` library.

I'll let you know when we have confirmed a fix and made a new release of the extension.

**Comment by thegecko** [comment]
Hi @VVESTM 

A new release of the device manager (v1.6.0) has been made with a potential fix for this issue.

Would you mind checking this has improved your experience?

**Comment by VVESTM** [comment]
Hi, yes, it is better, tested today with 1.6.1, thanks for your help !

I have one last issue, but it may be my fault or a "normal" behaviour...
I had trouble to detect the board while plug / unplug when I have several instances of VS Code running in the same time. The device is not detected by all of them.

**Comment by thegecko** [comment]
> I had trouble to detect the board while plug / unplug when I have several instances of VS Code running in the same time. The device is not detected by all of them.

We've seen this too. The recent release makes this a little better, but as far as we can see, there isn't a way to message between VS Code instances and get a refresh to happen when a change happens. We could add a polling mechanism to fix this, but feels like a dirty fix!

**Comment by VVESTM** [comment]
OK, so if this is a VS Code limitation and not this extension anymore, feel free to close the issue.

**Comment by thegecko** [comment]
> OK, so if this is a VS Code limitation and not this extension anymore, feel free to close the issue.

Thanks, I'll close the ticket for now, but we will continue to look into the window state issue.

**Comment by VVESTM** [comment]
Thanks
