### ISSUE TITLE
Browser crashes at the attempt of flashing device

### ISSUE THREAD

**Issue by AmiBelly** [ARM-software/vscode-device-manager#12]
Type: Bug Report

**Describe the bug**
- OS and Version: Github Codespaces
- VS Code Version: 1.9
- Extension Version: arm device manager 1.13.0
- Target Device: CY8CPROTO-062-4343W
- Other extensions you installed (and if the issue persists after disabling them): arm embedded debugger, C/C++
- Currently when flashing my device from Github Codespaces the browser crashes, tried edge/Chrome same tried using other device and other PCs still the browser crashes. I have tried to flash the device locally and it succeeded.
You can access the environment from here https://github.com/AmiBelly/mtb-example-hal-hello-world 

**To Reproduce**
1. Go to https://github.com/AmiBelly/mtb-example-hal-hello-world
2. Click on Open in Github Codespaces
3. make build according to your device code built for CY8CPROTO-062-4343W
4. also noticed the automatic installation of arm doesn't detects the device or work properly, need to manually delete and install manually both from arm device manager and arm embedded debugger
5. Switch the device to dap mode
6. add the device from arm device manager 
![image](https://github.com/ARM-software/vscode-device-manager/assets/164159676/02baafa3-0afe-4563-8f23-2013aadf5225)
7. go to build folder and look for .hex file and right clock to flash device one line message is displayed then the browser crashes

**Expected behavior**
expected that the device would flash and the light blinks

**Comment by thegecko** [comment]
Thanks for the feedback.

Issues for flashing should ideally be raised in https://github.com/ARM-software/vscode-embedded-debug/issues as that is the extension which undertakes flashing.

Would you mind outlining any log output you see during this process? There should be some feedback in the output window (with the Arm embedded debug channel selected)

**Comment by AmiBelly** [comment]
As mentioned I don't even manage to see any output except for this line, the whole browser crashes after in a matter of 2 seconds 
![image](https://github.com/ARM-software/vscode-device-manager/assets/164159676/bc9b6417-c255-4202-8600-6891f6f3ef74)
I also attached the .dmp file which didn't give me much info 
[ba9a94e6-0f3f-4aa6-8c79-03d4a5291013.dmp](https://github.com/user-attachments/files/15913105/ba9a94e6-0f3f-4aa6-8c79-03d4a5291013.dmp)

**Comment by thegecko** [comment]
Thanks for the details.

I happen to have that board and tried your workspace. I built the application from the terminal using `make build`.

With the device selected in device manager,  I used the context menu to flash the device as you did:

<img width="604" alt="Screenshot 2024-06-20 at 14 44 17" src="https://github.com/ARM-software/vscode-device-manager/assets/61341/689cc769-4048-4756-9bf5-9501a774da42">

The system then asks which core to flash:

<img width="730" alt="Screenshot 2024-06-20 at 14 44 26" src="https://github.com/ARM-software/vscode-device-manager/assets/61341/20d0cf32-4767-4fa6-82ac-0923654ecaa9">

And the flash proceeds.

<img width="512" alt="Screenshot 2024-06-20 at 14 44 32" src="https://github.com/ARM-software/vscode-device-manager/assets/61341/33847a6e-1dd8-42e8-bb56-36dad264fc46">

There seems to be a failure when confirming the flash however and this is beyond my immediate knowledge!

<img width="515" alt="Screenshot 2024-06-20 at 14 44 47" src="https://github.com/ARM-software/vscode-device-manager/assets/61341/b2ffad16-4063-4dd7-9b27-ddadb4046d43">

There is one key difference which I may have in my codespace and this is a known bug with extensions. The device manager and embedded debug extensions must be installed in the browser host. I think they default to the codespace host even though they are browser extensions. To do this, uninstall them and reinstall them again from the extensions search. This is how it should look:

<img width="404" alt="Screenshot 2024-06-20 at 14 50 33" src="https://github.com/ARM-software/vscode-device-manager/assets/61341/e27c3ef4-02ed-422c-8732-8d6ff59d3594">

<img width="439" alt="Screenshot 2024-06-20 at 14 51 30" src="https://github.com/ARM-software/vscode-device-manager/assets/61341/83ba2a80-7587-41f3-971f-9e3b99db7a2f">

**Comment by thegecko** [comment]
For completeness, the extension host problem was raised here: https://github.com/orgs/community/discussions/41636

**Comment by AmiBelly** [comment]
Thank you Rob for your reply,
Actually if you notice my notes I did mention in point 4 (To reproduce section) that I do uninstall both these extensions and install them manually.
What I noticed is that you attempted to flash .elf files, for me the crashing is happening when flashing the .hex file. Can you please try to reproduce with the .hex and give me your feedback

**Comment by thegecko** [comment]
> Actually if you notice my notes I did mention in point 4 (To reproduce section) that I do uninstall both these extensions and install them manually.

👍 

> What I noticed is that you attempted to flash .elf files, for me the crashing is happening when flashing the .hex file. Can you please try to reproduce with the .hex and give me your feedback

This will only work with DAPLink compatible devices, I've not seen this method work for the cypress devices I'm afraid. Does the elf/axf flash method work for you?

**Comment by AmiBelly** [comment]
Hi Rob, 
Sorry for the late reply, the elf flash is not working for me. Same with error message you are getting 
![image](https://github.com/ARM-software/vscode-device-manager/assets/164159676/e35dd6cc-b2c6-40ea-a52c-51b3e50ed43f)
Regarding the .hex files flashing I don't understand why it doesn't work for DAPLink devices when 5-6 months ago it was working and I was able to flash my device with the .hex files. 

Small addition, I have tested flashing the device locally with the .hex files and it works

**Comment by thegecko** [comment]
Further investigation has shown you are right and there is a general problem with DAPLink flash.

Thanks for raising the issue, we have a fix and plan to roll this out in the next release.

**Comment by thegecko** [comment]
Fixed in v1.2.1
