### ISSUE TITLE
Does not work properly in WSL2

### ISSUE THREAD

**Issue by syc0000000** [ARM-software/vscode-device-manager#13]
Type: Bug Report

**Describe the bug**
- OS and Version: Windows 11 with latest WSL2
- VS Code Version: 1.90.2
- Extension Version: 1.13.0
- Target Device: STM32 F103C8

I can't find my device when I use Arm Keil Studio Pack in VScode with WSL2. At the same time, openOCD or st-info in WSL2 can work with my device properly.
It seems that the extension Arm Device Manager declares itself to work locally on Windows instead of WSL.
![image](https://github.com/ARM-software/vscode-device-manager/assets/112924913/0b587363-97fe-4e72-9f91-9113d5e76906)
But If I don't use usbipt to connect my stlink into WSL2, the device can be discovered by the extension, but I also can't download my program to my board. It reports "device not found". 

I noticed there is an option like this screenshot.
![image](https://github.com/ARM-software/vscode-device-manager/assets/112924913/807fa5fb-6252-4aa9-bdf8-dde97c68de2a)
Actrully, I don't really understand what dose the option mean. What is "**VS code Extension Host**" instead of "VS Code's local Extension Host" or "Remote Extension Host"? (https://code.visualstudio.com/api/advanced-topics/remote-extensions#architecture-and-extension-kinds)
But whether I use it or not, it dosen't work properly.

By the way, I use usbipt to connect my stlink into WSL2. It work properly with OpenOCD or st-info
![image](https://github.com/ARM-software/vscode-device-manager/assets/112924913/a2f6cf13-b4cb-4545-8139-6d051a3a1e2c)

**Screenshots**
![image](https://github.com/ARM-software/vscode-device-manager/assets/112924913/e35f2c79-901d-4ad8-9cb3-090576beb254)

**Comment by thegecko** [comment]
Thanks for raising this @syc0000000 

> It seems that the extension Arm Device Manager declares itself to work locally on Windows instead of WSL.

This is correct, the device manager runs entirely on the local host, not the remote. So in your case it runs in Windows. This is to ensure device connection is local no matter where your remote is (locally, WSL, codespaces, etc.)

> But If I don't use usbipt to connect my stlink into WSL2, the device can be discovered by the extension...

We haven't tested our extensions with usbipt

> ...but I also can't download my program to my board. It reports "device not found".

What method are you using to download your program?

> I noticed there is an option like this screenshot "Use extension host".

This stops isolation of device access in workers, it doesn't change your setup so should be kept unchecked.

We ship 2 debugger extensions which can flash your hardware:

- Arm Debugger (default shipped with Keil Studio Pack) which will run in the remote and needs proxying out (I assume this is what usbipt does?)
- Embedded Debug, which runs in the same place as the device manager (local host)

When using WSL, I would recommend the following:

- With physical hardware, use embedded-debug if your device is supported (I think yours is) as this will be simpler
- With virtual hardware, use Arm Debugger as it always runs in the same extension host as the model
- If you want to use Arm Debugger for physical devices, you'll need to proxy it out and you may need to set the serialnumber manually in the config

**Comment by thegecko** [comment]
I've just checked on wsl2 that the serial number can be returned in the remote when the device-manager is local. This is the task I used:

```json
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "shell",
			"label": "test",
			"command": "echo ${command:device-manager.getSerialNumber}",
			"problemMatcher": []
		}
	]
}

```

You can use this approach to craft a task for executing whatever command you need. My only other thought is that using usbipt is claiming your device so it isn't available locally any more.

**Comment by syc0000000** [comment]
> Thanks for raising this @syc0000000
> 
> > It seems that the extension Arm Device Manager declares itself to work locally on Windows instead of WSL.
> 
> This is correct, the device manager runs entirely on the local host, not the remote. So in your case it runs in Windows. This is to ensure device connection is local no matter where your remote is (locally, WSL, codespaces, etc.)
> 
> > But If I don't use usbipt to connect my stlink into WSL2, the device can be discovered by the extension...
> 
> We haven't tested our extensions with usbipt
> 
> > ...but I also can't download my program to my board. It reports "device not found".
> 
> What method are you using to download your program?
> 
> > I noticed there is an option like this screenshot "Use extension host".
> 
> This stops isolation of device access in workers, it doesn't change your setup so should be kept unchecked.
> 
> We ship 2 debugger extensions which can flash your hardware:
> 
> * Arm Debugger (default shipped with Keil Studio Pack) which will run in the remote and needs proxying out (I assume this is what usbipt does?)
> * Embedded Debug, which runs in the same place as the device manager (local host)
> 
> When using WSL, I would recommend the following:
> 
> * With physical hardware, use embedded-debug if your device is supported (I think yours is) as this will be simpler
> * With virtual hardware, use Arm Debugger as it always runs in the same extension host as the model
> * If you want to use Arm Debugger for physical devices, you'll need to proxy it out and you may need to set the serialnumber manually in the config


Thank you. I think using embedded-debug instead of default Arm Debugger will work. The explain you said are all correct.
BTW, Putting this notice on Keil Studio Pack vscode extension page would be useful.
> * Arm Debugger (default shipped with Keil Studio Pack) which will run in the remote and needs proxying out (I assume this is what usbipt does?)
> * Embedded Debug, which runs in the same place as the device manager (local host)

**Comment by thegecko** [comment]
Closing as resolved
