### ISSUE TITLE
Customized Device Not Detected

### ISSUE THREAD

**Issue by vindicatorr** [ARM-software/vscode-device-manager#3]
First, I know the extension works, as it has found my STM32F4-Discovery board without any issues...

With that said, I however am unable to see my nrf52840 dongle.
Full disclosure with me having customized my dongle to use the mcuboot bootloader and a zephyr blinky app.

I am going with the assumption that the USB device's VID:PID is the determining factor for which device is valid? I only say that because part of my customization was to change the PID to 0x5221 (I think it would normally be 0x5220).

I'm only trying this now because I'm looking to use JTAG/SWD for my rockchip device, and am exploring using CMSIS directly to (hopefully) write something that'll flip whatever switches I need to inside the chip to make that happen.
I've peeked at CMSIS in the past, but never did anything with it as I've always been able to use the vendors' SDKs (st, nordicsemi, espressif) to accomplish what I needed to.

**Comment by thegecko** [comment]
Hi @vindicatorr 

As you surmise, we do restrict management of devices to known families of boards by default. However this can be switched off with the `Device Manager: Manage All Devices` extension setting.

Please be aware, this can affect stability as the extension will try to enumerate all USB devices (including system ones).

This should allow your device to be managed, let us know how you get on.

**Comment by vindicatorr** [comment]
Yeah, I had already enabled that and there was no change.
I also changed logging to `Debug` and from a reload get:
```
USB service starting
USB service running
Reading state selectedDevice: undefined
Reading state selectedDevice: undefined
device-manager:isDeviceSelected - false
device-manager:isDaplink - false
device-manager:hasDevicePack - false
Reading state selectedDevice: undefined
Reading state devices: <SN/ID of **un**plugged STM32>
```

And when I plug in my dongle, in the journal:
```
Apr 27 11:33:39 devx64 kernel: usb 3-4: new full-speed USB device number 20 using xhci_hcd
Apr 27 11:33:39 devx64 kernel: usb 3-4: New USB device found, idVendor=1915, idProduct=5221, bcdDevice= 3.03
Apr 27 11:33:39 devx64 kernel: usb 3-4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Apr 27 11:33:39 devx64 kernel: usb 3-4: Product: USB-DEV
Apr 27 11:33:39 devx64 kernel: usb 3-4: Manufacturer: ZEPHYR
Apr 27 11:33:39 devx64 kernel: usb 3-4: SerialNumber: <SN>
Apr 27 11:33:39 devx64 kernel: cdc_acm 3-4:1.0: ttyACM0: USB ACM device
Apr 27 11:33:39 devx64 kernel: cdc_acm 3-4:1.2: ttyACM1: USB ACM device
Apr 27 11:33:39 devx64 mtp-probe[4016203]: checking bus 3, device 20: "/sys/devices/pci0000:00/0000:00:14.0/usb3/3-4"
Apr 27 11:33:39 devx64 mtp-probe[4016203]: bus: 3, device: 20 was not an MTP device
Apr 27 11:33:39 devx64 mtp-probe[4016221]: checking bus 3, device 20: "/sys/devices/pci0000:00/0000:00:14.0/usb3/3-4"
Apr 27 11:33:39 devx64 mtp-probe[4016221]: bus: 3, device: 20 was not an MTP device
```

And then back to the extension log when trying to add it after plugged in: `Reading state devices: <SN/ID of **un**plugged STM32>`. Yes, the stm32, not my dongle.

And just for due diligence and shiggles, I enabled the last 2 settings, and no change in result either.

**Comment by thegecko** [comment]
And your dongle doesn't appear when you select `add device`?

My guess is you are on Windows?

Is your dongle connected via a USB bridge/adapter?

**Comment by vindicatorr** [comment]
No dongle shows in my extension (nothing does other than my stm32 when I connect it).
Nope, Linux here.
No bridge/adapter. Straight connection into the USB port of my motherboard.

EDIT0: I don't know if there's some magic going on in the probing that my zephyr blinker isn't providing response to.

**Comment by thegecko** [comment]
Perhaps you could try `lsusb` or similar tools to make sure the device is seen by the OS?

Udev rules?

**Comment by vindicatorr** [comment]
Nope, it's all good.
I don't know if you noticed the journal log output showing the USB connecting.
And I already had the rule to account for my PID change so I can access it as a user (no sudo needed).
And for completeness, the `lsusb` output: `Bus 003 Device 025: ID 1915:5221 Nordic Semiconductor ASA USB-DEV`

**Comment by thegecko** [comment]
My guess is your device fails to load properly. I'd need to add some further logging to confirm where any failure is.

Another option is we can test your firmware (pretty sure we have an nrf52840).

**Comment by thegecko** [comment]
One other thing which you can try is to use the web version of the extension (I assume you are in VS Code Desktop?)

If you open https://vscode.dev, install the same extensions and set the `Device Manager: Manage All Devices` setting, is it found?

This will help focus the investigation.

**Comment by vindicatorr** [comment]
At some point (while installing extension?), I got:
```
Error loading webview: Error: Could not register service worker. Please make sure third party cookies are enabled: NotSupportedError: Failed to register a ServiceWorker for scope ('https://1bitk9ejib7amr48ucl76bg3bn4u449go3t270r6m4rkvh2j2o62.vscode-cdn.net/stable/704ed70d4fd1c6bd6342c436f1ede30d1cff4710/out/vs/workbench/contrib/webview/browser/pre/') with script ('https://1bitk9ejib7amr48ucl76bg3bn4u449go3t270r6m4rkvh2j2o62.vscode-cdn.net/stable/704ed70d4fd1c6bd6342c436f1ede30d1cff4710/out/vs/workbench/contrib/webview/browser/pre/service-worker.js?v=4&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&remoteAuthority='): The user denied permission to use Service Worker.
```
... though I see the extension.
`No compatible devices found`
But when I plug in my stm32: `STM32 STLink`.

EDIT0: OOO! At least in there, when I change the settings to "Manage All Devices", it DOES show 6 devices (of which those that aren't particularly descriptive `USB-DEV`, `USB Receiver`, `Bluetooth Radio` (which may be that BT on my motherboard)).

EDIT1: Maybe it matters that I'm using:
```
Version: 1.75.0
Commit: 4c0cecf300334511c6ef64f40ba584dcbe3a03de
Date: 2022-12-31T19:22:05.944Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 6.2.1-dirty
Sandboxed: No
```
and `arm.device-manager v1.7.1`

**Comment by thegecko** [comment]
Not sure what the error is.

Also surprised you had nothing in the list with the `manage all devices` setting on :/

OK, this didn't help. Feel free to share your firmware (if you are happy to), otherwise we'll investigate further logging.

**Comment by thegecko** [comment]
We've released a new version containing further logging and a potential bug fix in this area. Keen to know if you see any different behaviour.

**Comment by vindicatorr** [comment]
Okay, got the same result with `v1.7.2`, however I went ahead and just {un,re}installed the extension and got changes (different than the web vscode though...).
```
USB service starting
USB service running
Reading state selectedDevice: undefined
Reading state selectedDevice: undefined
device-manager:isDeviceSelected - false
device-manager:isDaplink - false
device-manager:hasDevicePack - false
Reading state selectedDevice: undefined
Reading state devices: <stm32 SN>
Reading state devices: <stm32 SN>
Devices changed
Reading state selectedDevice: undefined
device-manager:isDeviceSelected - false
device-manager:isDaplink - false
device-manager:hasDevicePack - false
Reading state selectedDevice: undefined
Reading state selectedDevice: undefined
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
Reading state devices: <stm32 SN>
Reading state devices: <stm32 SN>
Reading state customNames: undefined
Reading state customNames: undefined
```

And this time, when I enabled `Manage All Devices`, I got a listing which included 2 devices (instead of the 6 when using web vscode).

When I re-plugged my dongle, I saw that it was `USB DEV` that was the one that changed, which would also align with the `Bus 003 Device 032: ID 1915:5221 Nordic Semiconductor ASA **USB-DEV**` part.

Though hovering over the device, it looks like you have the VID:PID in decimal form instead of hex.

The log expanded to:
```
Reading state devices: <stm32 SN>
Reading state customNames: undefined
Reading state customNames: undefined
Reading state selectedDevice: undefined
Devices changed
Reading state selectedDevice: undefined
device-manager:isDeviceSelected - false
device-manager:isDaplink - false
device-manager:hasDevicePack - false
Reading state selectedDevice: undefined
Reading state selectedDevice: undefined
Reading state devices: <stm32 SN>
Reading state devices: <stm32 SN>
Reading state customNames: undefined
Reading state devices: <stm32 SN>
Reading state customNames: undefined
Reading state devices: <stm32 SN>
Reading state customNames: undefined
Reading state customNames: undefined
Reading state devices: <stm32 SN>
Writing state devices: <stm32 SN>|<dongle SN>
Writing state selectedDevice: <dongle SN>
Devices changed
Reading state selectedDevice: <dongle SN>
Reading state devices: <stm32 SN>|<dongle SN>
Reading state selectedDevice: <dongle SN>
Reading state devices: <stm32 SN>|<dongle SN>
device-manager:isDeviceSelected - true
device-manager:isDaplink - false
device-manager:hasDevicePack - false
Reading state selectedDevice: <dongle SN>
Reading state devices: <stm32 SN>|<dongle SN>
Reading state customNames: undefined
Reading state selectedDevice: <dongle SN>
Reading state devices: <stm32 SN>|<dongle SN>
undefined
Devices changed
Reading state selectedDevice: <dongle SN>
Reading state devices: <stm32 SN>|<dongle SN>
Reading state selectedDevice: <dongle SN>
Reading state devices: <stm32 SN>|<dongle SN>
device-manager:isDeviceSelected - true
device-manager:isDaplink - false
device-manager:hasDevicePack - false
Reading state selectedDevice: <dongle SN>
Reading state devices: <stm32 SN>|<dongle SN>
Reading state customNames: undefined
Reading state selectedDevice: <dongle SN>
Reading state devices: <stm32 SN>|<dongle SN>
Reading state devices: <stm32 SN>|<dongle SN>
Reading state customNames: undefined
Reading state selectedDevice: <dongle SN>
Reading state devices: <stm32 SN>|<dongle SN>
Reading state customNames: undefined
Reading state selectedDevice: <dongle SN>
Reading state devices: <stm32 SN>|<dongle SN>
Reading state customNames: undefined
Reading state customNames: undefined
Reading state devices: <stm32 SN>|<dongle SN>
Reading state baudRates: undefined
Reading state customNames: undefined
Reading state baudRates: undefined
Writing state baudRates: {"<dongle SN>":"115200"}
Reading state selectedDevice: <dongle SN>
Reading state devices: <stm32 SN>|<dongle SN>
Reading state selectedDevice: <dongle SN>
Reading state devices: <stm32 SN>|<dongle SN>
```

I'm getting `Writing login information to the keychain failed with error 'Timeout was reached'.` and am not sure if that relates to this extension or vscode (https://code.visualstudio.com/docs/editor/settings-sync#_troubleshooting-keychain-issues).
I'm not seeing ANY active `sync` settings, other than `Git:*` stuff, of which none are "active" (makes git do something automatically) settings.
Is this extension doing/needing to sync anything?

I had updated my vscode yesterday to:
```
Version: 1.78.0
Commit: c455231128790ee8d78305f327483273b25d7cdf
Date: 2023-04-28T01:30:32.842Z
Electron: 22.3.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 6.2.1-dirty
Sandboxed: Yes
```
but believe I was also getting the timeout notification with the previous version. However, I believe I had the extension previously disabled after previous testing in the past, and hadn't been getting any timeouts in that time.

Some asides:
Regarding `[daplink](device-manager:isDaplink - false)`, I'm only starting to get a little familiar with DAP, I came across it in the TRM for my rockchip device where it mentioned `daplite2`, and me trying to get it to work using my stm32 SWD and openocd.
What condition is needed to get it to the `isDaplink - true` state?

I was curious about the `Open Serial` button, but when I pressed it, and selected the `Baud rate`, nothing happened and the Problem,Output,... panel closed.
The second time I tried it (just now), it switched to the Terminal tab, but that just remained at my command prompt in the project dir.
I also just got that `Timeout was reached` message again. It's odd that no message about the attempt shows up in the journal.
I use keepassxc, and whenever anything needs to do keyring stuff like my browser or an electron app, they always trigger KP, via the `Secret Service Integration`, to have me unlock it and confirm it's use before proceeding.

For shiggles, I connected my radxa rock-5b USB in maskrom mode to see if it would show as a device (since it references daplite2 in the manual). It does not...:
```
Bus 003 Device 035: ID 2207:350b Fuzhou Rockchip Electronics Company
```
Also with the same curiosity, since I noticed my smartphone was in the list, I went ahead and selected that and tried serial with it, but it just brings up the `Serial port` list, of which there was none for my smartphone (though I do use ADB with it).
Yeah, more and more, I'm thinking that `timeout` is related to the extension, particularly when I'm trying to do serial stuff. When I had that `Serial port` list open and was scanning through it, I got the keychain timeout message and almost immediately after got a "no serial port selected" notification when I clicked out of the list. Though that could just be coincidence of my deliberately clicking out of serial after I got the keychain timeout.
But as I'm composing all of this, I'm not getting any other "timeout" notification, and the timespan in which I test "serial", and coming back here to write more is different and I'd expect I'd get the timeout while I'm typing/searching.

Hmm, looking at the README again, I see `A Terminal tab opens with the baud rate selected.`, so I guess it's to be expected that the panel switches to the Terminal tab, and nothing happens?
I did a `printenv` to look for any mention of the baud rate, and there was nothing.
I was just assuming it was going to do some special/magical serial connection immediately instead of just bringing us to the Terminal tab where we do it all manually (minicom,screen,...).

**Comment by thegecko** [comment]
Ok, wow...

> different than the web vscode though...

Yeah, there would be no change unless your device supports webusb. There will likely be a difference when listing online due to libusb support on the desktop, system devices, etc. IUf your device doesn't support webusb (USB interface type 255 I think), let';s ignore the web side of things for now.

> Though hovering over the device, it looks like you have the VID:PID in decimal form instead of hex

Hovering where? does your device appear in the UI now?

> Is this extension doing/needing to sync anything?

No, this is unrelated

> What condition is needed to get it to the isDaplink - true state?

You need to be running DAPLink based firmware. This isn't a prerequisite for using your device if it supports CMSIS-DAP. 

> I was curious about the Open Serial button

Is your device outputting serial information?

> immediately after got a "no serial port selected"...
I guess it's to be expected that the panel switches to the Terminal tab, and nothing happens?

Thats because no port was selected. The system tries to intelligently find the serial port for the device, but it's possible its on a completely different com port, so if not found it offers a list of all ports to choose from see #2 

> I was just assuming it was going to do some special/magical serial connection immediately

It does, I just assume your device isnt printing anything?


There's a lot of data in your comment above. It would be good if you could outline your issue a little more concisely.

With the latest update, can you now see and select your device?

For serial output to appear, your application needs to be writing to the port.

**Comment by vindicatorr** [comment]
> Yeah, there would be no change unless your device supports webusb

Sounds like I would get more results with the desktop than with the web, but it's the inverse.

> Hovering where? does your device appear in the UI now?

Um, yeah? Hence my mention of `USB DEV`. But even then, I still would've had my stm32 show.
It wasn't until I {un,re}installed the 1.7.2 that it started to show the other devices after also enabling `Manage All Devices`.
"...hovering over the device"? in the extension panel?

> No, this is unrelated

I'm still going to question if that's the case, as I've had the extension disabled and had been working on a c/cpp project, for hours and that notification has yet to come up.

> You need to be running DAPLink based firmware.

Is that for the interface (stm32) or the target (nrf, rockchip, ...)? I've got my stm32 firmware flashed to the latest, but get the `false` status. I'll have to poke around st.com to see if there's any `daplink` specific firmware for any of their offerings.

> Is your device outputting serial information?

I'll have to take a look at "blink" code, but I'd think if I'm just brought to the "TERMINAL" tab in the vscode panel, with only a shell prompt, no serial data is going to be displayed.

> The system tries to intelligently find the serial port for the device

That was just for the stm32. For my nrf52 dongle, it never asked for the port because like you said, it already figured it out (though for the dongle I've got 2 ttyACMs, so no clue if the "intelligence" is taking that into account).

> It would be good if you could outline your issue a little more concisely.
Yeah, it was a bit lengthy and spread over multiple things, but I'm not sure how much I could've cut it down without you needing to ask questions (which you apparently still needed to).

Based on the overview "This extension allows you to manage device connections for Arm Cortex-M based microcontrollers, development boards and debug probes.", I guess I was under the misconception of what it actually does, and it appears that I'm just better off sticking with the old tried-and-true openocd/gdb/screen method I've already been doing.

**Comment by thegecko** [comment]
> Sounds like I would get more results with the desktop than with the web, but it's the inverse.

I am so confused. You got this working in the web version?

> Is that for the interface (stm32) or the target (nrf, rockchip, ...)? 

I'm also unclear how you have everything set up. If you are using an stm32 interface chip, what firmware is that running? STLink, DAPLink.

If you can outline whats connected where and the firmware its running I can try to help specify a task/launch config to flash or debug your device on desktop or web.

**Comment by vindicatorr** [comment]
> I am so confused. You got this working in the web version?

In response to your "you can try is to use the web version", me: "OOO! At least in there, when I change the settings to "Manage All Devices", it DOES show 6 devices"
Then later me: "I got a listing which included 2 devices (instead of the 6 when using web vscode)." in reference to using the desktop extension.
Both are "working"(? finding some devices at least). It seems that for some inexplicable reason, {un,re}installing the extension did the trick, because upgrading to 1.7.2 alone did not do it (even when I had `Manage All Devices` enabled. I even mentioned enabling everything), which I'm just repeating myself from "...however I went ahead and just {un,re}installed the extension..."

I've had my setup different depending on the purpose. For example, to flash MCUBOOT as the main bootloader, I used my stm32 SWD to write to the dongle.
After that, I think I just used `mcumgr` via the USB port to flash programs for mcuboot to run.

I've already been doing all of that in vscode with no issues and without using extensions (other than the standard c_cpp one). I just fire up openocd and gdb in the launcher, and have-at-it in vscode.

The curiosity that brought me back to this extension was me trying to work with my rockchip device that the TRM states handles DAPLITE2 (again, all mentioned earlier), but I had no clue how to do any SWD stuff with it, as nothing I did in u-boot or anything did anything.
I've progressed on that aspect and don't believe the BOOTROM is set up to do any SWD by itself and I think I'm nearing completion of getting a program ready to manipulate the registers to get JTAG/SWD to work.

> what firmware is that running? STLink, DAPLink.

Darned if I know. `en.stsw-link007-v3-12-3.zip` was the last thing I flashed to upgrade my stm32 firmware.
But with openocd, I've been using `interface/stlink.cfg` just fine. When I recently learned about DAP, and how it "appears" to be the "next thing", I saw there was also a `interface/stlink-dap.cfg`, and I *think* I may have already tried that and it too worked, but I'll be trying again at some later point after dealing with this rockchip fiasco.

I'm good. I've moved on. Again, like I've said, I think I just had a misconception of what this extension does. I know I've said a lot, and we don't need to spend anymore time on this.

**Comment by thegecko** [comment]
OK, thanks.

`en.stsw-link007-v3-12-3.zip` is used to flash STLink which is interface firmware from ST and not DAPLink.

This means the flashing mode is slightly different, but should work. If you do come back to this extension, I've realised you may not have the flash/debug part installed. We explicitly have this split into a different extension to help developers compose the environment they want (rather than just having everything all in one extension).

- arm.device-manager - used to discover and select a connected device
- arm.embedded-debug - used to flash and debug a device

Both of the above work in a browser VS Code environment and desktop VS Code environment.

Thanks for trying the extension, please raise a new issue if you need further support.
