### ISSUE TITLE
Various targets on one STLink-V2

### ISSUE THREAD

**Issue by Aptahar** [ARM-software/vscode-device-manager#8]
When work with many projects where targets are different (different STM32 and GD32), you need to reconfigure STLink-V2 connection every time after switching between projects.  
It would be more convenient to add devices to the list by target, not by STLink through which it connects to VScode.

**Comment by thegecko** [comment]
Thanks for your feedback, this is an interesting suggestion.

Perhaps separating a target configuration from a specific serial number would solve this. It would need some thought with regards to flows such as what happens when a user plugs in a device.

**Comment by Aptahar** [comment]
Or maybe device manager somehow would detect which CMSIS pack needed for target in project

**Comment by jreineckearm** [comment]
> Or maybe device manager somehow would detect which CMSIS pack needed for target in project

You can use the `${command:cmsis-csolution.getTargetPack}` command in your `launch.json`/`tasks.json` files if you are using the Arm CMSIS Solution extension for project management. This will give you the CMSIS DFP for the currently active build context.

See for example:
https://github.com/Arm-Examples/Blinky_FRDM-K32L3A6/blob/main/.vscode/launch.json#L13
https://github.com/Arm-Examples/Blinky_FRDM-K32L3A6/blob/main/.vscode/tasks.json#L8

**Comment by Aptahar** [comment]
> You can use the `${command:cmsis-csolution.getTargetPack}` command in your `launch.json`/`tasks.json` files if you are using the Arm CMSIS Solution extension for project management. This will give you the CMSIS DFP for the currently active build context.

Ok, that's works.
Changed `"cmsisPack": "${command:device-manager.getDevicePack}"` to `"cmsisPack": "${command:cmsis-csolution.getTargetPack}"` in tastks.json and launch.json
Maybe add this feature to the converter from uVision projects, by default it creates these files with `"${command:device-manager.getDevicePack}"
`

**Comment by thegecko** [comment]
> Maybe add this feature to the converter from uVision projects, by default it creates these files with "${command:device-manager.getDevicePack}" 

cc @jkrech
